// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeJpyS5yElt2kUbyAEDVH_TiRJEKkDqfo',
    appId: '1:1032766533514:web:a0561438d9aad4eaaae273',
    messagingSenderId: '1032766533514',
    projectId: 'calmawear-81263',
    authDomain: 'calmawear-81263.firebaseapp.com',
    storageBucket: 'calmawear-81263.firebasestorage.app',
    measurementId: 'G-96HGSBXJ0E',
    databaseURL: 'https://calmawear-81263-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR4cM2hp0VfkyKlR5hk-eI_16Eq7TIQ8w',
    appId: '1:1032766533514:android:ae70d77578b53898aae273',
    messagingSenderId: '1032766533514',
    projectId: 'calmawear-81263',
    storageBucket: 'calmawear-81263.firebasestorage.app',
    databaseURL: 'https://calmawear-81263-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqE0a8Isd8TKXKT1LXUSfSLDRPd1IVCwE',
    appId: '1:1032766533514:ios:c81f9487780f9f15aae273',
    messagingSenderId: '1032766533514',
    projectId: 'calmawear-81263',
    storageBucket: 'calmawear-81263.firebasestorage.app',
    iosBundleId: 'com.example.calmaWear',
    databaseURL: 'https://calmawear-81263-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqE0a8Isd8TKXKT1LXUSfSLDRPd1IVCwE',
    appId: '1:1032766533514:ios:c81f9487780f9f15aae273',
    messagingSenderId: '1032766533514',
    projectId: 'calmawear-81263',
    storageBucket: 'calmawear-81263.firebasestorage.app',
    iosBundleId: 'com.example.calmaWear',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeJpyS5yElt2kUbyAEDVH_TiRJEKkDqfo',
    appId: '1:1032766533514:web:641738813eddd630aae273',
    messagingSenderId: '1032766533514',
    projectId: 'calmawear-81263',
    authDomain: 'calmawear-81263.firebaseapp.com',
    storageBucket: 'calmawear-81263.firebasestorage.app',
    measurementId: 'G-0EMLN5NCR6',
    databaseURL: 'https://calmawear-81263-default-rtdb.firebaseio.com',
  );
}
